language: python
dist: trusty

install:
  - pip install codecov
  - pip install mkdocs
  - pip install tox

jobs:
  include:
    - stage: build
      name: "Build"
      script: tox --notest --sdistonly
    - name: "Generating documentation"
      script: mkdocs build --clean


#    - stage: "Tests"
#      name: "Test 1"
#      script: tox --parallel all
#    - stage: deploy
#      deploy:
#        provider: pypi



