language: python
dist: trusty


install:
  - pip install codecov
        
jobs:
  include:
    - stage: build
      name: "Build"
      install: pip install tox
      script: tox --notest --sdistonly
#    - name: "Generating documentation"
#      install: pip install mkdocs
#      script: mkdocs build --clean


    - stage: "Tests"  
      name: "Test py35-integration"
      python: '3.5'
      env: TOXENV=py35-integration
      install:
        - pip install codecov
        - pip install tox
      script: tox
    - name: "Test py35-min-req"
      python: '3.5'
      env: TOXENV=py35-min-req
      install:
        - pip install codecov
        - pip install tox
      script: tox
    - name: "Test py35-unittests"
      python: '3.5'
      env: TOXENV=py35-unittests
      install:
        - pip install codecov
        - pip install tox
      script: tox 
    - name: "Test py36"
      python: "3.6"
      env: TOXENV=py36
      install:
        - pip install codecov
        - pip install tox
      script: tox
    
    
#    - stage: deploy
#      deploy:
#        provider: pypi



