language: python
dist: trusty

install:
  - pip install codecov
        
jobs:
  include:
    - stage: build
      name: "Build"
      python: '3.6'
      install: pip install tox
      script: tox --notest --sdistonly
    - name: "Generating documentation"
      python: '3.6'
      script: 
        - pydoc -w ./mkdocs


    - stage: "Tests"  
      name: "Test py35"
      python: '3.5'
      env: TOXENV=py35
      install:
        - pip install codecov
        - pip install tox
      script: tox

    - name: "Test py36"
      python: "3.6"
      env: TOXENV=py36
      install:
        - pip install codecov
        - pip install tox
      script: tox
    
    
    - stage: deploy
      script: skip
      deploy:
        provider: pages
        local-dir: ./docs/
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master



