language: python
dist: trusty

install:
  - pip install codecov
  - pip install tox

jobs:
  include:
    - stage: build
      script: 
        git clean -f -d -x
        tox --notest --sdist-only”


#    - stage: "Tests"
#      name: "Test 1"
#      script: tox --parallel all
#    - stage: deploy
#      deploy:
#        provider: pypi



