language: python
dist: trusty

install:
  - pip install codecov
  - pip install -U Sphinx
  - pip install tox

jobs:
  include:
    - stage: build
      name: "Build"
      script: tox --notest --sdistonly
    - name: "Generating documentation"
      script: sphinx-build -d "doc/docs_doctree" doc "doc/docs_out" --color -W -bhtml


#    - stage: "Tests"
#      name: "Test 1"
#      script: tox --parallel all
#    - stage: deploy
#      deploy:
#        provider: pypi



