language: python
dist: trusty

install:
  - pip install codecov
#  - pip install mkdocs
  - pip install tox
        
jobs:
  include:
    - stage: build
      name: "Build"

      script: tox --notest --sdistonly
#    - name: "Generating documentation"
#      script: mkdocs build --clean


    - stage: "Tests"  
      name: "Test py35"
      script: tox -e py35
    - name: "Test py36"
      script: tox -e py36
    
    
#    - stage: deploy
#      deploy:
#        provider: pypi



