language: python
dist: trusty


install:
  - pip install codecov
        
jobs:
  include:
    - stage: build
      name: "Build"
      install: pip install tox
      script: tox --notest --sdistonly
#    - name: "Generating documentation"
#      install: pip install mkdocs
#      script: mkdocs build --clean


    - stage: "Tests"  
      name: "Test py35"
      python: "3.5"
      env: TOXENV=py35tests
      install:
        - pip install codecov
        - pip install tox
      script: tox --result-json
    - name: "Test py36"
      python: "3.6"
      env: TOXENV=py36tests
      install:
        - pip install codecov
        - pip install tox
      script: tox --result-json
    
    
#    - stage: deploy
#      deploy:
#        provider: pypi



