language: python
dist: trusty


install:
  - pip install codecov
        
jobs:
  include:
    - stage: build
      name: "Build"
      install: pip install tox
      script: tox --notest --sdistonly
#    - name: "Generating documentation"
#      install: pip install mkdocs
#      script: mkdocs build --clean


    - stage: "Tests"  
      name: "Test py35"
      python: "3.5"
      install:
        - pip install codecov
        - pip install tox
      script: tox -e py35test
    - name: "Test py36"
      python: "3.6"
      install:
        - pip install codecov
        - pip install tox
      script: tox -e py36test
    
    
#    - stage: deploy
#      deploy:
#        provider: pypi



